### ISSUE TITLE
Gestion Token

### ISSUE THREAD

**Issue by gaetan1903** [iTeam-S/BJJ-Library#2]
- Cas d'expiration Token 

  _Redirection vers le login en affichant un message Session expiré_ 

  _A chaque ouverture de l'application régénéré le token d'utilisateur_

**Comment by Landris18** [comment]
Je crois que c'est déjà reglé , on doit fermer cette issue @gaetan1903

**Comment by gaetan1903** [comment]
Tu as ajouté la fonctionnalité 😅 ce n'est pas encore fait de mon côté... 🥴
